language: python

python:
  - "3.6"

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/1.23.2/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose build

before_script:
  - sudo /etc/init.d/postgresql stop

script:
 - docker-compose run django python manage.py test